version: '3'
services:
  hysteria2:
    image: tobyxdd/hysteria:latest
    container_name: hysteria2
    restart: always
    network_mode: host
    volumes:
      - ./config/config.yaml:/etc/hysteria/config.yaml
      - /etc/letsencrypt:/etc/letsencrypt:ro
