listen: :443
protocol: udp

tls:
  cert: /etc/letsencrypt/live/vpn.example.com/fullchain.pem
  key: /etc/letsencrypt/live/vpn.example.com/privkey.pem
  alpn:
    - h3
    - h2
    - http/1.1
  sni: rr3---sn-i3belnez.googlevideo.com

auth:
  type: password
  password: your-strong-password

obfs:
  type: salamander
  password: obfs-secret

bandwidth:
  up: 100 mbps
  down: 100 mbps
